src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Ausi\SlugGenerator\SlugGenerator;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug():string
    {
        return (new SlugGenerator)->generate($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    //recuperer le type de chauffage utilisé
    public function getHeatType():string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('sold')
            ->add('rooms')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/biens", name="property.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request):Response
    {
        /*$property = new Property();
        $property->setTitle('Mon premier bien')
            ->setAddress('22 Rue Mermoz')
            ->setBedrooms(3)
            ->setCity('Dakar')
            ->setDescription('Une petite description')
            ->setHeat(1)
            ->setFloor(4)
            ->setPostalCode(12500)
            ->setPrice(200000)
            ->setSurface(60)
            ->setRooms(4);
        //Creer le gestionnaire d'entités
        $em = $this->getDoctrine()->getManager();
        // Persister l'entité property
        $em->persist($property);
        //porter tous les changement faits sur l'entity manager dans la base de donnee
        $em->flush();*/
        //recuperer proprietes par id
        //$property = $this->repository->find(1);
        //recuperer all properties
        //$property = $this->repository->findAll();
        //recuperer all properties where ...
        //$property = $this->repository->findOneBy(['floor' => 4]);

        //recuperer all properties non vendue
        /*$property = $this->repository->findAllVisible();
        dump($property);*/

        //Modifier entité
        /* $property[0]->setSold(true);
         $this->em->flush();*/
        //$properties = $this->repository->findAllVisible();

        ###### Creer un Search Engine pour les proprietes ######
        //Creer une entité qui va représenter notre recherche
        //Entity/PropertySearch.php
        //Creer un formulaire
        //php bin/console make:form Form/PropertySearchType.php
        // modifier builder, resolver et creer function prefixe
        //Gerer le traitement sur le controller
        //creer new objet PropertySearch() et new form PropertySearchType
        //forme execute la requette et on envoi le form a la vue
        //on affiche le form dans la vue et on va
        //dans PropertyRepository pour modifier la requete findAllVisibleQuery
        //il prend l'entité PropertySearch et renvoi un Query
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            6
        );
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug":"[a-zA-Z0-9\-]*"})
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    //Affiche la propriete avec son slug et son id dans le lien
    public function show(Property $property, string $slug):Response
    {
        //verifie si les slug correspondent Si non corrige le bon et fait une redirect permanante sur le lien canonique
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
               'id' =>$property->getId(),
                'slug' =>$property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
           'current_menu' => 'properties'
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
        </h5>
        <p class="card-text">
            {{ property.description | nl2br }}
        </p>
        <p class="card-text">
            Surface: {{ property.surface }} m<sup>2</sup>
        </p>
        <p class="card-text">
            Ville: {{ property.city }}
        </p>
        <p class="card-text">
            Code Postal: ({{ property.postalCode }})
        </p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem">
            {{ property.formatedPrice}}
            CFA
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Tous les biens | Proprietes | Agence Loren Ipsum' %}

{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col-md-4">
                    {{ form_row(form.minSurcace) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.options) }}
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <button class="btn btn-primary btn-block">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
        <h1>Voir tous nos biens</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis eligendi itaque labore laboriosam laborum maiores minima nesciunt repellat unde voluptatum. Asperiores, excepturi incidunt magni maxime molestiae omnis quod reprehenderit velit?</p>
    </div>

    <div class="container">
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8"></div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
                    <div class="text-primary" style="font-size: 3rem; font-weight: bold">{{ property.formatedPrice }} CFA</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface Habitable</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>
{% endblock %}